- name: configure the catalogue server
  hosts: local
  become: yes
  tasks:
  - name: install the nodejs 20v package
    ansible.builtin.command: dnf module install nodejs:20 -y
  - name: create the roboshop system user
    vars:
      username: roboshop
    ansible.builtin.user:
      name: roboshop
      comment: creation of system user
      shell: /sbin/nologin
      home: /app
    when: username != roboshop
