[local]
172.31.28.49

[mongodb]
mongodb.devsecops86s.space

[catalogue]
catalogue.devsecops86s.space

[frontend]
devsecops86s.space

[all:vars]
ansible_user=ec2-ansible_user
ansible-password=DevOps321